export const USER_FETCH="USER_FETCH";
export const USER_FETCH_SUCCESS="USER_FETCH_SUCCESS";
export const USER_FETCH_FAILURE="USER_FETCH_FAILURE";

export const GET_SINGLE_USER="GET_SINGLE_USER";
export const GET_SINGLE_USER_SUCCESS="GET_SINGLE_USER_SUCCESS";
export const GET_SINGLE_USER_FAILURE="GET_SINGLE_USER_FAILURE";